
export const categoryConstants = {
  GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_FAILURE: "GET_CATEGORY_FAILURE",

  ADD_CATEGORY_REQUEST:"ADD_CATEGORY_REQUEST",
  ADD_CATEGORY_SUCCESS:"ADD_CATEGORY_SUCCESS",
  ADD_CATEGORY_FAILURE:"ADD_CATEGORY_FAILURE",
  
  DEL_CATEGORY_REQUEST:"DEL_CATEGORY_REQUEST",
  DEL_CATEGORY_SUCCESS:"DEL_CATEGORY_SUCCESS",
  DEL_CATEGORY_FAILURE:"DEL_CATEGORY_FAILURE",


  EDIT_CATEGORY_REQUEST:"EDIT_CATEGORY_REQUEST",
  EDIT_CATEGORY_SUCCESS:"EDIT_CATEGORY_SUCCESS",
  EDIT_CATEGORY_FAILURE:"EDIT_CATEGORY_FAILURE",


};

export const courseConstants ={
  GET_COURSE_REQUEST: "GET_COURSE_REQUEST",
  GET_COURSE_SUCCESS: "GET_COURSE_SUCCESS",
  GET_COURSE_FAILURE: "GET_COURSE_FAILURE",

  EDIT_COURSE_REQUEST: "EDIT_COURSE_REQUEST",
  EDIT_COURSE_SUCCESS: "EDIT_COURSE_SUCCESS",
  EDIT_COURSE_FAILURE: "EDIT_BRAND_FAILURE",

  DEL_COURSE_REQUEST: "DEL_COURSE_REQUEST",
  DEL_COURSE_SUCCESS: "DEL_COURSE_SUCCESS",
  DEL_COURSE_FAILURE: "DEL_COURSE_FAILURE",

  ADD_COURSE_REQUEST:"ADD_COURSE_REQUEST",
  ADD_COURSE_SUCCESS:"ADD_COURSE_SUCCESS",
  ADD_COURSE_FAILURE:"ADD_COURSE_FAILURE",



}
export const showroomConstants ={
  GET_SHOWROOM_REQUEST: "GET_SHOWROOM_REQUEST",
  GET_SHOWROOM_SUCCESS: "GET_SHOWROOM_SUCCESS",
  GET_SHOWROOM_FAILURE: "GET_SHOWROOM_FAILURE",

  ADD_SHOWROOM_REQUEST: "ADD_SHOWROOM_REQUEST",
  ADD_SHOWROOM_SUCCESS: "ADD_SHOWROOM_SUCCESS",
  ADD_SHOWROOM_FAILURE: "ADD_SHOWROOM_FAILURE",

  DEL_SHOWROOM_REQUEST: "DEL_SHOWROOM_REQUEST",
  DEL_SHOWROOM_SUCCESS: "DEL_SHOWROOM_SUCCESS",
  DEL_SHOWROOM_FAILURE: "DEL_SHOWROOM_FAILURE",

  EDIT_SHOWROOM_REQUEST: "EDIT_SHOWROOM_REQUEST",
  EDIT_SHOWROOM_SUCCESS: "EDIT_SHOWROOM_SUCCESS",
  EDIT_SHOWROOM_FAILURE: "EDIT_SHOWROOM_FAILURE",

}
export const helmetConstants = {
  GET_HELMET_REQUEST: "GET_HELMET_REQUEST",
  GET_HELMET_SUCCESS: "GET_HELMET_SUCCESS",
  GET_HELMET_FAILURE: "GET_HELMET_FAILURE",
}
export const productConstants = {
  GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
  ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",
};

export const helemtbrandConstants ={
  GET_HELMET_BRAND_REQUEST: "GET_HELMET_BRAND_REQUEST",
  GET_HELMET_BRAND_SUCCESS: "GET_HELMET_BRAND_SUCCESS",
  GET_HELMET_BRAND_FAILURE: "GET_HELMET_BRAND_FAILURE",

  EDIT_HELMET_BRAND_REQUEST: "EDIT_HELMET_BRAND_REQUEST",
  EDIT_HELMET_BRAND_SUCCESS: "EDIT_HELMET_BRAND_SUCCESS",
  EDIT_HELMET_BRAND_FAILURE: "EDIT_HELMET_BRAND_FAILURE",

  DEL_HELMET_BRAND_REQUEST: "DEL_HELMET_BRAND_REQUEST",
  DEL_HELMET_BRAND_SUCCESS: "DEL_HELMET_BRAND_SUCCESS",
  DEL_HELMET_BRAND_FAILURE: "DEL_HELMET_BRAND_FAILURE",

  ADD_HELMET_BRAND_REQUEST:"ADD_HELMET_BRAND_REQUEST",
  ADD_HELMET_BRAND_SUCCESS:"ADD_HELMET_BRAND_SUCCESS",
  ADD_HELMET_BRAND_FAILURE:"ADD_HELMET_BRAND_FAILURE",



}
