
export const categoryConstants = {
  GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_FAILURE: "GET_CATEGORY_FAILURE",

  ADD_CATEGORY_REQUEST:"ADD_CATEGORY_REQUEST",
  ADD_CATEGORY_SUCCESS:"ADD_CATEGORY_SUCCESS",
  ADD_CATEGORY_FAILURE:"ADD_CATEGORY_FAILURE",
  
  DEL_CATEGORY_REQUEST:"DEL_CATEGORY_REQUEST",
  DEL_CATEGORY_SUCCESS:"DEL_CATEGORY_SUCCESS",
  DEL_CATEGORY_FAILURE:"DEL_CATEGORY_FAILURE",


  EDIT_CATEGORY_REQUEST:"EDIT_CATEGORY_REQUEST",
  EDIT_CATEGORY_SUCCESS:"EDIT_CATEGORY_SUCCESS",
  EDIT_CATEGORY_FAILURE:"EDIT_CATEGORY_FAILURE",


};

export const courseConstants ={
  GET_COURSE_REQUEST: "GET_COURSE_REQUEST",
  GET_COURSE_SUCCESS: "GET_COURSE_SUCCESS",
  GET_COURSE_FAILURE: "GET_COURSE_FAILURE",

  EDIT_COURSE_REQUEST: "EDIT_COURSE_REQUEST",
  EDIT_COURSE_SUCCESS: "EDIT_COURSE_SUCCESS",
  EDIT_COURSE_FAILURE: "EDIT_BRAND_FAILURE",

  DEL_COURSE_REQUEST: "DEL_COURSE_REQUEST",
  DEL_COURSE_SUCCESS: "DEL_COURSE_SUCCESS",
  DEL_COURSE_FAILURE: "DEL_COURSE_FAILURE",

  ADD_COURSE_REQUEST:"ADD_COURSE_REQUEST",
  ADD_COURSE_SUCCESS:"ADD_COURSE_SUCCESS",
  ADD_COURSE_FAILURE:"ADD_COURSE_FAILURE",



}
export const paymentConstants ={
  GET_PAYMENT_REQUEST: "GET_PAYMENT_REQUEST",
  GET_PAYMENT_SUCCESS: "GET_PAYMENT_SUCCESS",
  GET_PAYMENT_FAILURE: "GET_PAYMENT_FAILURE",

  DEL_PAYMENT_REQUEST: "DEL_PAYMENT_REQUEST",
  DEL_PAYMENT_SUCCESS: "DEL_PAYMENT_SUCCESS",
  DEL_PAYMENT_FAILURE: "DEL_PAYMENT_FAILURE",

  EDIT_PAYMENT_REQUEST: "EDIT_PAYMENT_REQUEST",
  EDIT_PAYMENT_SUCCESS: "EDIT_PAYMENT_SUCCESS",
  EDIT_PAYMENT_FAILURE: "EDIT_PAYMENT_FAILURE",

}
export const modelTestConstants = {
  GET_MODELTEST_REQUEST: "GET_MODELTEST_REQUEST",
  GET_MODELTEST_SUCCESS: "GET_MODELTEST_SUCCESS",
  GET_MODELTEST_FAILURE: "GET_MODELTEST_FAILURE",
}
export const userConstants = {
  GET_ALL_USER_REQUEST: "GET_ALL_USER_REQUEST",
  GET_ALL_USER_SUCCESS: "GET_ALL_USER_SUCCESS",
  GET_ALL_USER_FAILURE: "GET_ALL_USER_FAILURE",

  DEL_USER_REQUEST: "DEL_USER_REQUEST",
  DEL_USER_SUCCESS: "DEL_USER_SUCCESS",
  DEL_USER_FAILURE: "DEL_USER_FAILURE",
};

