
export const userConstants = {

  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",


  USER_LOGOUT_REQUEST :"USER_LOGOUT_REQUEST",
  USER_LOGOUT_SUCCESS : "USER_LOGOUT_SUCCESS",

  PROFILE_UPDATE_REQUEST : "PROFILE_UPDATE_REQUEST",
  PROFILE_UPDATE_SUCCESS : "PROFILE_UPDATE_SUCCESS",
  PROFILE_UPDATE_FAILURE : "PROFILE_UPDATE_FAILURE"
}
export const courseConstants = {
  GET_COURSE_REQUEST : "GET_COURSE_REQUEST",
  GET_COURSE_SUCCESS : "GET_COURSE_SUCCESS",
  GET_COURSE_FAILURE : "GET_COURSE_FAILURE"
};

export const paymentConstants ={
  MAKE_PAYMENT_REQUEST : "MAKE_PAYMENT_REQUEST",
  MAKE_PAYMENT_SUCCESS : "MAKE_PAYMENT_SUCCESS",
  MAKE_PAYMENT_FAILURE : "MAKE_PAYMENT_FAILURE",


  GET_PAYMENT_DETAILS_REQUEST : "GET_PAYMENT_DETAILS_REQUEST",
  GET_PAYMENT_DETAILS_SUCCESS : "GET_PAYMENT_DETAILS_SUCCESS",
  GET_PAYMENT_DETAILS_FAILURE : "GET_PAYMENT_DETAILS_FAILURE"

}
